return {
    id = nil;
    
    name = "test mod";
    author = "laof"; --obvious
    --richtext support
    description = "yes, a test. or is it, i have no idea!! but is it test or test i honeslty dont know so dont ask ever, even in the commit message alright..";
    categories = {
        "map";
        "autorun";
    } ;

    iconID = "rbxassetid://135527769310887"; --1:1 "rbxassetid://replaceid"
    gallery = { --16:9 "rbxassetid://replaceid";
        "rbxassetid://75628710390998";
    };

    modfile = "";
}