return {
    id = nil;

    name = "testmod 2";
    author = "laof"; --obvious
    --richtext support
    description = `<s>test here</s> run this fake code from <font color="#ff0000"><b><i>rich</i></b> </font>text support: <font color="#52c5ff">print</font>(<font color="#1eff00">"yes test 2 i will yea"</font>)`;
    categories = {
        "autorun";
        "client";
    } ;

    iconID = "rbxassetid://135527769310887"; --1:1 "rbxassetid://replaceid"
    gallery = { --16:9 "rbxassetid://replaceid";
        "rbxassetid://75628710390998";
    };

    modfile = "";
}